/**
 * profile_viewer.js — Genius Data Profile & Composition Report
 *
 * Renders:
 *   1. Genius Executive Composition Card:
 *      - Overall Data Health Score (0-100) with visual color badge
 *      - Completeness % across all cells
 *      - Executive Insights generated by the composition engine
 *      - Relational Discovery (shared keys / cross-table joins)
 *   2. KPI Strip
 *   3. Unified Column Schema Catalog / Dictionary
 *   4. Per-table profile tabs (Column types, Evidence, Anomalies, Mismatches)
 *   5. Unparsed rows & Raw JSON viewer
 */

export function renderProfile(result) {
  const profileSection = document.getElementById('profile-section');
  profileSection.classList.add('visible');

  let section = profileSection.querySelector('.container');
  if (!section) {
    section = document.createElement('div');
    section.className = 'container';
    profileSection.appendChild(section);
  }
  section.innerHTML = '';
  section.classList.add('fade-in');

  const { stage1, stage2, filename } = result;

  if (!stage2) {
    section.innerHTML = `<div class="status-banner visible error"><span>❌ Stage 2 profiling data is missing from the response.</span></div>`;
    return;
  }

  // --- Section title ---
  section.appendChild(el('div', { className: 'section-title' }, [
    '🧠 Universal Data Profile & Composition',
  ]));
  section.appendChild(el('p', { className: 'section-subtitle' },
    [`Intelligent schema extraction and composition for "${filename}" — ${stage2.total_tables} table(s) analyzed`]
  ));

  // --- Genius Composition Summary Card ---
  if (stage2.composition) {
    section.appendChild(buildCompositionCard(stage2.composition, filename));
  } else {
    // Fallback human summary
    const summaryCard = el('div', { className: 'summary-card' });
    summaryCard.innerHTML = `<pre class="summary-pre">${escHtml(stage2.human_summary)}</pre>`;
    section.appendChild(summaryCard);
  }

  // --- KPI Strip ---
  section.appendChild(buildKpiStrip(stage2));

  // --- Stage-level warnings ---
  if (stage2.warnings && stage2.warnings.length) {
    stage2.warnings.forEach(w => {
      const banner = el('div', { className: 'status-banner visible info' });
      banner.innerHTML = `<span>ℹ️ ${escHtml(w)}</span>`;
      section.appendChild(banner);
    });
  }

  // --- Unified Column Schema Catalog ---
  if (stage2.composition?.unified_columns?.length) {
    section.appendChild(buildUnifiedSchemaCatalog(stage2.composition.unified_columns));
  }

  // --- Per-table tabs ---
  if (stage2.table_profiles && stage2.table_profiles.length > 0) {
    const tabBar = el('div', { className: 'tab-bar' });
    const tabPanels = el('div', {});

    stage2.table_profiles.forEach((tp, i) => {
      const label = tp.source_sheet
        ? `${tp.source_sheet}`
        : tp.source_page
          ? `Page ${tp.source_page} / Table ${tp.table_index + 1}`
          : `Table ${tp.table_index + 1}`;

      const tabBtn = el('button', {
        className: `tab-btn ${i === 0 ? 'active' : ''}`,
        id: `tab-btn-${i}`,
        type: 'button',
        onclick: () => activateTab(i, stage2.table_profiles.length),
      }, [label]);
      tabBar.appendChild(tabBtn);

      const panel = el('div', {
        className: `tab-panel ${i === 0 ? 'active' : ''}`,
        id: `tab-panel-${i}`,
      });

      panel.appendChild(buildTableProfile(tp, stage1, i));
      tabPanels.appendChild(panel);
    });

    const tablesHeading = el('h2', { style: 'margin: 36px 0 14px; font-size:1.15rem;' }, ['📑 Extracted Tables Profile']);
    section.appendChild(tablesHeading);
    section.appendChild(tabBar);
    section.appendChild(tabPanels);
  }

  // --- Unparsed rows panel ---
  const allUnparsed = [...(stage1.unparsed_rows || [])];
  if (allUnparsed.length > 0) {
    section.appendChild(buildUnparsedPanel(allUnparsed));
  }

  // --- Raw JSON ---
  section.appendChild(buildJsonPanel(result));
}


// ---------------------------------------------------------------------------
// Genius Composition Card Builder
// ---------------------------------------------------------------------------

function buildCompositionCard(comp, filename) {
  const card = el('div', { className: 'composition-card' });

  // Determine health color & label
  let healthColor = '#10B981'; // green
  let healthLabel = 'EXCELLENT INTEGRITY';
  if (comp.health_score < 70) {
    healthColor = '#EF4444'; // red
    healthLabel = 'QUALITY ALERT';
  } else if (comp.health_score < 88) {
    healthColor = '#F59E0B'; // amber
    healthLabel = 'MODERATE INTEGRITY';
  }

  card.innerHTML = `
    <div class="composition-header">
      <div class="composition-title-group">
        <div class="composition-badge">GENIUS COMPOSITION</div>
        <div class="composition-filename">📁 ${escHtml(filename)}</div>
      </div>
      <div class="composition-health-gauge">
        <div class="health-score-val" style="color:${healthColor};">${comp.health_score}<span class="score-max">/100</span></div>
        <div class="health-score-label" style="color:${healthColor};">${healthLabel}</div>
      </div>
    </div>

    <div class="composition-metrics-grid">
      <div class="comp-metric-item">
        <span class="comp-metric-label">Completeness</span>
        <span class="comp-metric-val">${comp.completeness_pct}%</span>
        <div class="comp-meter-track">
          <div class="comp-meter-fill" style="width:${comp.completeness_pct}%;background:${healthColor};"></div>
        </div>
      </div>
      <div class="comp-metric-item">
        <span class="comp-metric-label">Total Records</span>
        <span class="comp-metric-val">${comp.total_records.toLocaleString()}</span>
      </div>
      <div class="comp-metric-item">
        <span class="comp-metric-label">Unique Features</span>
        <span class="comp-metric-val">${comp.total_features} cols</span>
      </div>
      <div class="comp-metric-item">
        <span class="comp-metric-label">Schema Unification</span>
        <span class="comp-metric-val" style="color:${comp.can_unify ? '#10B981' : '#94A3B8'};">
          ${comp.can_unify ? '✅ Unifiable' : 'Independent'}
        </span>
      </div>
    </div>

    <div class="composition-insights-section">
      <div class="insights-title">💡 Executive Insights &amp; Findings:</div>
      <ul class="insights-list">
        ${comp.executive_insights.map(i => `<li>${escHtml(i)}</li>`).join('')}
      </ul>
    </div>

    ${comp.table_relationships && comp.table_relationships.length ? `
      <div class="relationships-section">
        <div class="relationships-title">🔗 Discovered Relational Keys:</div>
        <div class="relationship-pills">
          ${comp.table_relationships.map(r => `
            <span class="rel-pill">
              <span class="rel-table">${escHtml(r.table_a)}</span>
              <span class="rel-arrow">⇄</span>
              <span class="rel-table">${escHtml(r.table_b)}</span>
              <span class="rel-key">on [${escHtml(r.matching_column)}]</span>
            </span>
          `).join('')}
        </div>
      </div>
    ` : ''}
  `;

  return card;
}


// ---------------------------------------------------------------------------
// Unified Column Schema Catalog
// ---------------------------------------------------------------------------

function buildUnifiedSchemaCatalog(columns) {
  const wrap = el('div', { className: 'schema-catalog-wrap' });
  wrap.innerHTML = `
    <div class="schema-catalog-header">
      <div style="font-size:1.05rem;font-weight:700;">🧬 Column Schema Dictionary (${columns.length} Features)</div>
      <input type="search" class="schema-search-input" placeholder="Filter columns by name or type…" />
    </div>
    <div class="schema-table-container">
      <table class="schema-table">
        <thead>
          <tr>
            <th>Column Header</th>
            <th>Inferred Type</th>
            <th>Confidence</th>
            <th>Null Rate</th>
            <th>Unique Values</th>
            <th>Sample Values</th>
          </tr>
        </thead>
        <tbody>
          ${columns.map(col => {
            const nullPct = col.total_count > 0 ? ((col.null_count / col.total_count) * 100).toFixed(0) : 0;
            const typeBadgeCls = `badge-type-${col.inferred_type}`;
            const samples = (col.sample_values || []).slice(0, 4).map(s => `<span class="sample-chip">${escHtml(String(s))}</span>`).join('');
            return `
              <tr class="schema-row" data-name="${escHtml(col.header.toLowerCase())}" data-type="${escHtml(col.inferred_type)}">
                <td style="font-weight:600;color:var(--text-primary);">${escHtml(col.header)}</td>
                <td><span class="type-badge ${typeBadgeCls}">${escHtml(col.inferred_type.toUpperCase())}</span></td>
                <td><span class="conf-pill">${(col.confidence * 100).toFixed(0)}%</span></td>
                <td>${nullPct}% (${col.null_count})</td>
                <td>${col.unique_count.toLocaleString()}</td>
                <td><div class="sample-chips-row">${samples || '<span style="color:var(--text-muted)">—</span>'}</div></td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>
    </div>
  `;

  const search = wrap.querySelector('.schema-search-input');
  search.addEventListener('input', e => {
    const q = e.target.value.trim().toLowerCase();
    wrap.querySelectorAll('.schema-row').forEach(row => {
      const name = row.getAttribute('data-name');
      const type = row.getAttribute('data-type');
      row.style.display = (!q || name.includes(q) || type.includes(q)) ? '' : 'none';
    });
  });

  return wrap;
}


// ---------------------------------------------------------------------------
// KPI Strip
// ---------------------------------------------------------------------------

function buildKpiStrip(stage2) {
  const kpis = [
    { value: stage2.total_tables,       label: 'Tables Found',      icon: '📊' },
    { value: stage2.total_detail_rows,  label: 'Detail Rows',       icon: '🗂' },
    { value: stage2.total_categories,   label: 'Distinct Values',   icon: '🏷' },
    { value: stage2.total_anomalies,    label: 'Anomalies',         icon: '🔍',
      accent: stage2.total_anomalies > 0 ? '#F87171' : null },
    { value: stage2.total_mismatches,   label: 'Total Mismatches',  icon: '⚠️',
      accent: stage2.total_mismatches > 0 ? '#FBBF24' : null },
  ];

  const strip = el('div', { className: 'kpi-strip' });
  kpis.forEach(k => {
    const card = el('div', { className: 'kpi-card' });
    card.innerHTML = `
      <div style="font-size:1.4rem;margin-bottom:6px;">${k.icon}</div>
      <div class="kpi-value" style="${k.accent ? `color:${k.accent}` : ''}">${k.value.toLocaleString()}</div>
      <div class="kpi-label">${escHtml(k.label)}</div>
    `;
    strip.appendChild(card);
  });
  return strip;
}


// ---------------------------------------------------------------------------
// Per-table profile builder
// ---------------------------------------------------------------------------

function buildTableProfile(tp, stage1, idx) {
  const wrap = el('div', {});

  // Meta row
  const meta = el('div', { className: 'table-meta-bar' });
  const rawTable = stage1.tables[tp.table_index];
  const items = [
    `Rows: ${tp.total_rows.toLocaleString()} (${tp.detail_row_count} detail)`,
    `Columns: ${tp.column_profiles.length}`,
    `Grain: ${escHtml(tp.grain_description || '—')}`,
    `Hierarchy: ${tp.has_hierarchy ? 'Yes' : 'No'}`,
  ];
  if (rawTable?.extraction_method) {
    items.unshift(`Method: ${rawTable.extraction_method}`);
  }
  meta.innerHTML = items.map(t => `<span class="meta-item">${t}</span>`).join('');
  wrap.appendChild(meta);

  // Time structure note
  if (tp.time_structure) {
    const ts = tp.time_structure;
    const banner = el('div', { className: 'time-banner' });
    banner.innerHTML = `
      <span>⏳ <b>Time Structure Detected:</b> ${escHtml(ts.period_type || '')} periods
      from <b>${escHtml(ts.start || '')}</b> to <b>${escHtml(ts.end || '')}</b>
      (${ts.count} period columns).</span>
    `;
    wrap.appendChild(banner);
  }

  // Column Profiles table
  const colTable = buildColumnProfilesTable(tp.column_profiles);
  wrap.appendChild(colTable);

  // Anomalies panel
  wrap.appendChild(buildAnomaliesPanel(tp.anomalies || []));

  // Computed column mismatches panel
  wrap.appendChild(buildMismatchesPanel(tp.computed_column_mismatches || []));

  return wrap;
}


function buildColumnProfilesTable(colProfiles) {
  const wrap = el('div', { style: 'overflow-x:auto; margin-top:20px;' });
  const tbl = el('table', { className: 'col-profiles-table' });
  tbl.innerHTML = `
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Inferred Type</th>
        <th>Confidence</th>
        <th>Nulls</th>
        <th>Unique</th>
        <th>Sample Values</th>
        <th>Type Evidence</th>
      </tr>
    </thead>
    <tbody>
      ${colProfiles.map((cp, i) => `
        <tr>
          <td style="color:var(--text-muted);">${i + 1}</td>
          <td><b>${escHtml(cp.header)}</b>${cp.is_computed_column ? ' <span class="chip chip-computed">COMPUTED</span>' : ''}</td>
          <td><span class="type-badge badge-type-${cp.inferred_type}">${cp.inferred_type}</span></td>
          <td><span class="conf-pill">${(cp.type_confidence * 100).toFixed(0)}%</span></td>
          <td>${cp.null_count}</td>
          <td>${cp.unique_count}</td>
          <td style="font-size:0.8rem;color:var(--text-code);">${escHtml((cp.sample_values || []).slice(0, 3).join(', ') || '—')}</td>
          <td style="font-size:0.8rem;color:var(--text-secondary);max-width:260px;">${escHtml(cp.type_evidence || '—')}</td>
        </tr>
      `).join('')}
    </tbody>
  `;
  wrap.appendChild(tbl);
  return wrap;
}


function buildAnomaliesPanel(anomalies) {
  const wrap = el('div', { style: 'margin-top:28px;' });
  const head = el('h3', { style: 'font-size:0.95rem; margin-bottom:10px;' });
  head.innerHTML = `🔍 Detected Anomalies <span class="chip" style="background:${anomalies.length ? 'rgba(239,68,68,0.15)' : 'rgba(16,185,129,0.15)'};color:${anomalies.length ? '#f87171' : '#10b981'};">${anomalies.length}</span>`;
  wrap.appendChild(head);

  if (!anomalies.length) {
    const p = el('p', { style: 'font-size:0.85rem; color:var(--success);' }, ['✅ No anomalies detected in this table.']);
    wrap.appendChild(p);
    return wrap;
  }

  const list = el('div', { className: 'anomaly-list' });
  anomalies.forEach(a => {
    const item = el('div', { className: 'anomaly-item' });
    item.innerHTML = `
      <div class="anomaly-header">
        <span class="anomaly-type">${escHtml(a.anomaly_type)}</span>
        ${a.col_header ? `<span class="anomaly-col">Col: ${escHtml(a.col_header)}</span>` : ''}
        ${a.row_index != null ? `<span class="anomaly-row">Row: ${a.row_index}</span>` : ''}
      </div>
      <div class="anomaly-desc">${escHtml(a.description)}</div>
      ${a.raw_value ? `<div class="anomaly-val">Raw value: <code>${escHtml(a.raw_value)}</code></div>` : ''}
    `;
    list.appendChild(item);
  });
  wrap.appendChild(list);
  return wrap;
}


function buildMismatchesPanel(mismatches) {
  const wrap = el('div', { style: 'margin-top:28px;' });
  const head = el('h3', { style: 'font-size:0.95rem; margin-bottom:10px;' });
  head.innerHTML = `⚠️ Computed Column Mismatches <span class="chip" style="background:${mismatches.length ? 'rgba(245,158,11,0.15)' : 'rgba(16,185,129,0.15)'};color:${mismatches.length ? '#fbbf24' : '#10b981'};">${mismatches.length}</span>`;
  wrap.appendChild(head);

  if (!mismatches.length) {
    const p = el('p', { style: 'font-size:0.85rem; color:var(--success);' }, ['✅ All computed columns matched recomputed sums.']);
    wrap.appendChild(p);
    return wrap;
  }

  const list = el('div', { className: 'mismatch-list' });
  mismatches.forEach(m => {
    const item = el('div', { className: 'mismatch-item' });
    const delta = m.delta || 0;
    const sign = delta >= 0 ? '+' : '';
    item.innerHTML = `
      <div style="font-weight:600;margin-bottom:8px;">
        Row: "${escHtml(m.row_description)}" — Col: "${escHtml(m.column_header)}"
      </div>
      <div class="mismatch-row">
        <div class="mismatch-val">
          <span class="mismatch-val-label">Source Value</span>
          <span>${fmt(m.source_value)}</span>
        </div>
        <div class="mismatch-val">
          <span class="mismatch-val-label">Recomputed Sum</span>
          <span>${fmt(m.recomputed_value)}</span>
        </div>
        <div class="mismatch-val">
          <span class="mismatch-val-label">Delta</span>
          <span style="color:${delta < 0 ? '#ef4444' : '#10b981'};font-weight:700;">${sign}${fmt(delta)}</span>
        </div>
      </div>
      <div class="mismatch-formula">${escHtml(m.recomputed_from)}</div>
    `;
    list.appendChild(item);
  });
  wrap.appendChild(list);
  return wrap;
}


function buildUnparsedPanel(rows) {
  const wrap = el('div', { style: 'margin-top:32px;' });
  const head = el('h3', { style: 'margin-bottom: 12px; font-size:0.95rem;' });
  head.innerHTML = `⛔ Unparsed Rows <span class="chip" style="background:rgba(239,68,68,0.1);color:#f87171;">${rows.length}</span>`;
  wrap.appendChild(head);

  rows.forEach(r => {
    const item = el('div', { className: 'unparsed-item' });
    item.innerHTML = `
      <div class="unparsed-source">Source: ${escHtml(r.source || '?')} — Reason: ${escHtml(r.reason || '?')}</div>
      <div class="unparsed-text">${escHtml((r.raw_text || '').substring(0, 400))}</div>
    `;
    wrap.appendChild(item);
  });

  return wrap;
}


function buildJsonPanel(result) {
  const details = document.createElement('details');
  details.style.marginTop = '32px';

  const summary = el('summary', {
    style: 'cursor:pointer; color:var(--text-muted); font-size:0.85rem; margin-bottom:12px; user-select:none;',
  }, ['🔧 Raw Pipeline JSON (debugging & integrations)']);
  details.appendChild(summary);

  const pre = el('div', { className: 'json-viewer' });
  pre.textContent = JSON.stringify(result, null, 2);
  details.appendChild(pre);

  return details;
}


// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function activateTab(activeIdx, total) {
  for (let i = 0; i < total; i++) {
    document.getElementById(`tab-btn-${i}`)?.classList.toggle('active', i === activeIdx);
    document.getElementById(`tab-panel-${i}`)?.classList.toggle('active', i === activeIdx);
  }
}

function el(tag, attrs = {}, children = []) {
  const e = document.createElement(tag);
  Object.entries(attrs).forEach(([k, v]) => {
    if (k === 'style' && typeof v === 'string') e.style.cssText = v;
    else if (k.startsWith('on') && typeof v === 'function') e.addEventListener(k.slice(2), v);
    else e[k] = v;
  });
  children.forEach(c => {
    if (typeof c === 'string') e.appendChild(document.createTextNode(c));
    else if (c instanceof Node) e.appendChild(c);
  });
  return e;
}

function escHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function fmt(n) {
  if (n === null || n === undefined) return '—';
  return Number(n).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
